MealPrep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meals.urls')), 
    path('', include('django.contrib.auth.urls')),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

meals/urls.py
from django.urls import path

from . import views

app_name = 'meals'
urlpatterns = [
    path('', views.Menu.as_view(), name='home'),

    path('recipes', views.RecipesView.as_view(), name='recipes'),
    path('recipe/', views.RecipeCreate.as_view(), name='recipe'),
    path('recipe-url/', views.RecipeUrlCreate.as_view(), name='recipe-url'),
    path('recipe/<int:pk>', views.Recipe.as_view(), name='recipe-view'),
    path('recipe/<int:pk>/update', views.RecipeUpdate.as_view(), name='recipe-update'),
    path('recipe/<int:pk>/delete', views.RecipeDelete.as_view(), name='recipe-delete'),

    path('menu', views.Menu.as_view(), name='menu'),
    path('grocery-list', views.GroceryList.as_view(), name='list'),
]

meals/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Recipes(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    url = models.URLField(blank=True, null=True)
    category = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    directions = models.TextField()
    prep_time_hr = models.IntegerField(blank=True, null=True)
    prep_time_min = models.IntegerField(blank=True, null=True)
    cook_time_hr = models.IntegerField(blank=True, null=True)
    cook_time_min = models.IntegerField(blank=True, null=True)
    total_time = models.IntegerField(blank=True, null=True)
    servings = models.CharField(max_length=255,blank=True, null=True)
    image = models.ImageField(upload_to='recipe_photos', null=True, blank=True)
    image_url = models.URLField(blank=True, null=True)

class Ingredients(models.Model):
    ingredient = models.CharField(max_length=255)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=255, null=True)

class Measurements(models.Model):
    measurement = models.CharField(max_length=255)

class Quantities(models.Model):
    quantity = models.CharField(max_length=255)

class RecipeIngredients(models.Model):
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredients, on_delete=models.CASCADE)
    measurement = models.ForeignKey(Measurements, on_delete=models.CASCADE)
    quantity = models.ForeignKey(Quantities, on_delete=models.CASCADE)

class RecipeTags(models.Model):
    recipe_id = models.ForeignKey(Recipes, on_delete=models.CASCADE)
    tag = models.CharField(max_length=255)

class RecipeFavorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE)

'''
# recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Recipe(models.Model):
  title = models.CharField(max_length=100)
  description = models.TextField()

  author = models.ForeignKey(User, on_delete=models.CASCADE)

  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.title
'''

meals/forms.py
from django import forms
from django.forms import ModelForm
from meals.models import Recipes, RecipeIngredients
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django.forms import formset_factory

class RecipeForm(ModelForm):
    class Meta:
        model = Recipes
        fields = '__all__'
        exclude = ('author',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['prep_time_hr'].label = ""
        self.fields['prep_time_min'].label = ""
        self.fields['cook_time_hr'].label = ""
        self.fields['cook_time_min'].label = ""

class RecipeIngredientsForm(forms.Form):
    ingredient = forms.CharField(max_length=100, required=False,
                                widget=forms.TextInput(attrs={'placeholder': 'Name of ingredient'}))
    measurement = forms.CharField(max_length=100, required=False,
                                widget=forms.TextInput(attrs={'placeholder': 'Cup, Tbs...'}))
    quantity = forms.FloatField(required=False,
                                widget=forms.TextInput(attrs={'placeholder': '1,2,3...'}))
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False

IngredientFormSet = formset_factory(RecipeIngredientsForm, extra=1)
        
class RecipeUrlForm(forms.Form):
    url = forms.URLField()

meals/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.forms import formset_factory

from .forms import RecipeForm, RecipeIngredientsForm, IngredientFormSet, RecipeUrlForm
from .models import Recipes, RecipeIngredients, Ingredients, Measurements, Quantities, RecipeTags
from .utils import saverecipeingredients

from recipe_scrapers import scrape_me

import re

# Create your views here.
class Menu(View):
    def get(self, request):
        return HttpResponse('Home')

class RecipesView(ListView):
        model = Recipes
        paginate_by = 12
        

class Recipe(View):
    def get(self, request, pk):
        recipe = Recipes.objects.get(pk=pk)
        ingredients = RecipeIngredients.objects.filter(recipe_id=pk)
        context = {'recipe': recipe, 'ingredients':ingredients}
        return render(request, 'meals/recipe.html', context)

class RecipeUrlCreate(View):
    def get(self, request):
        form = RecipeUrlForm()
        context = {'form': form}
        return render(request, 'meals/recipe_url_form.html', context)
    def post(self, request):
        form = RecipeUrlForm(request.POST)
        if not form.is_valid():
            context = {'form': form}
            return render(request, 'meals/recipe_url_form.html', context)

        new_recipe = Recipes()

        url = form.cleaned_data['url']
        scraper = scrape_me(url)


        new_recipe.title = scraper.title()
        new_recipe.author = request.user
        new_recipe.url = url
        # category = 
        # description = 
        new_recipe.directions = scraper.instructions()
        new_recipe.total_time = scraper.total_time()
        new_recipe.servings = scraper.yields()
        new_recipe.image_url = scraper.image()
        new_recipe.save()
        # tags
        # nutrients = scraper.nutrients()


        #add ingreidents to RecipeIngredients
        for x in scraper.ingredients():
            #print(x)
            match = re.search(r'\d[\d\s /]*(?=\s*[a-zA-Z])', x)
            if match:
                number = match.group()
                item = x[match.end():].strip()
                print(number)
                print(item)
            data = {}
            data['quantity'] = (x.split()[0])
            data['measurement'] = (x.split()[1])
            ingredient = (x.split()[2:])
            data['ingredient'] = ' '.join(ingredient)
            saverecipeingredients(data, new_recipe)
            


        #return HttpResponse('working')
        return redirect(reverse_lazy('meals:recipe-view', args=[new_recipe.id]))

class RecipeCreate(LoginRequiredMixin, View):
    def get(self, request):
        form = RecipeForm()
        formset = IngredientFormSet()
        context = {'form': form, 'formset': formset}
        return render(request, 'meals/recipe_form.html', context)

    def post(self, request):
        form = RecipeForm(request.POST, request.FILES)
        formset = IngredientFormSet(self.request.POST)
        
        if not form.is_valid():
            context = {'form': form, 'formset': formset}
            return render(request, 'meals/recipe_form.html', context)
        
        new_recipe = form.save(commit=False)
        new_recipe.author = request.user
        new_recipe.save()
        
        data = formset[0].data.dict()
        saverecipeingredients(data, new_recipe)
        return redirect(reverse_lazy('meals:recipe-view', args=[new_recipe.id]))

class RecipeUpdate(View):
    def get(self, request, pk):
        recipe = get_object_or_404(Recipes, pk=pk)
        form = RecipeForm(instance=recipe)
        ingredients = RecipeIngredients.objects.filter(recipe=pk)

        IngredientFormSet = formset_factory(RecipeIngredientsForm, extra=0)
        formset = IngredientFormSet(initial=[{'ingredient': ingredient.ingredient.ingredient, 'quantity': ingredient.quantity.quantity ,'measurement': ingredient.measurement.measurement} for ingredient in ingredients])
        
        context = {'form': form, 'formset': formset}
        return render(request, 'meals/recipe_form.html', context)
        return HttpResponse('RecipeEdit')

    def post(self, request, pk):
        recipe = get_object_or_404(Recipes, pk=pk)
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        formset = IngredientFormSet(self.request.POST)
        if not form.is_valid():
            context = {'form': form, 'formset': formset}
            return render(request, 'meals/recipe_form.html', context)
        #add author
        recipe = form.save(commit=False)
        recipe.author = request.user
        recipe.save()
        #remove old ingredients
        RecipeIngredients.objects.filter(recipe=recipe).delete()
        data = formset[0].data.dict()
        saverecipeingredients(data, recipe)
        return redirect(reverse_lazy('meals:recipe-view', args=[recipe.id]))

class RecipeDelete(View):
    def get(self, request, pk):
        recipe = Recipes.objects.get(pk=pk)
        ingredients = RecipeIngredients.objects.filter(recipe_id=pk)
        context = {'recipe': recipe, 'ingredients': ingredients, 'delete': True}
        return render(request, 'meals/recipe.html', context)
    def post(self, request, pk):
        Recipes.objects.get(pk=pk).delete()
        return redirect(reverse_lazy('meals:recipes'))

class GroceryList(View):
    def get(self, request):
        return HttpResponse('GroceryList')

meals/templates/meals/recipe.html
{% extends "base.html" %}
{% block content %}
{% if delete %}
<h2>Delete Recipe? </h2>
<form method="POST">
    {% csrf_token %}
    <button class="btn-primary btn" type="submit">Delete</button>
    <a href="{% url 'meals:recipe-view' recipe.id %}" class="btn btn-primary">Cancel</a>
</form>

{% endif %}
{% if recipe %}
    <h1 class="text-center">
        {{ recipe.title }}
    </h1>
    <p class="text-center">{{ recipe.category }}</p>
    <hr>
    <div class="row">
        <div class="col">
            <p>{{ recipe.description }}</p>
            {% if ingredients %}
                <h2>Ingredients</h2>
                {% for ingredient in ingredients %}
                    <ul>
                        <li>{{ingredient.quantity.quantity}} {{ingredient.measurement.measurement}} - {{ingredient.ingredient.ingredient}}</li>
                    </ul>  
                {% endfor %}
            {% endif %}
            <h2>Directions</h2>
            <div>{{recipe.directions}}</div>
        </div>
        <div class="col">
            {% if recipe.image%}
                    <img src="{{recipe.image.url}}" class="img-fluid" >
            {% endif %}
            {% if recipe.image_url%}
            <img src="{{recipe.image_url}}" class="img-fluid" >
            {% endif %}
            

            <div class="row">
                

                    <div class="col">
                        
                        <p>Prep Time: {{ recipe.prep_time_hr | default:"0"}} : {{ recipe.prep_time_min | default:"00" }} </p>
                        
                    </div>
                
                <div class="col">
                    <p>Cook Time {{ recipe.cook_time_hr | default:"0"}} : {{ recipe.cook_time_min | default:"00" }} </p></p>
                
                </div>

            </div>
            <div class="float-right">
                <a href="{% url 'meals:recipe-update' recipe.id %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'meals:recipe-delete' recipe.id %}" class="btn btn-primary">Delete</a>
            </div>
            
        </div>
    </div>
{% else %}
    <p>No recipe with that id</p>
{% endif %}

    

    
{% endblock %}

meals/templates/meals/recipe_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <h1 class="text-center">New Recipe</h1>
    <form id="recipeform" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{formset.management_form}}
        <div class="row">
            <div class="col">
                <h2 class="text-center">About</h2>
                {{ form.title | as_crispy_field }}
                {{ form.category | as_crispy_field }}
                {{ form.description | as_crispy_field }}
                {{ form.servings | as_crispy_field }}
                
                <div class="row">
                    <div class="col">
                        <label for="{{form.prep_time_hr.id_for_label}}">Prep Time</label>
                    </div>
                    <div class="col">
                        <label for="{{form.prep_time_hr.id_for_label}}">Cook Time</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div></div>
                    </div>
                    <div class="col">
                        <div></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="d-flex">
                            <div class="d-inline-block"> {{ form.prep_time_hr | as_crispy_field }} </div>
                            <div class="d-inline-block"> <h3>&nbsp;:&nbsp;</h3></div>
                            <div class="d-inline-block"> {{ form.prep_time_min | as_crispy_field }} </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="d-flex">
                            <div class="d-inline-block"> {{ form.cook_time_hr | as_crispy_field }} </div>
                            <div class="d-inline-block"> <h3>&nbsp;:&nbsp;</h3></div>
                            <div class="d-inline-block"> {{ form.cook_time_min | as_crispy_field }} </div>
                        </div>
                    </div>
                </div>
                <div>
                    {{ form.image | as_crispy_field }}
                </div>
            </div>

            <div id="form-container" class="col">
                <h2 class="text-center">Ingredients & Directions</h2>
                {{ form.directions | as_crispy_field }}
                <div class="form-row">
                    <div class="col-6">
                        Ingredient
                    </div>
                    <div class="col-2">
                        Quantity                       
                    </div>
                    <div class="col-3">
                        Measurement
                    </div>      
                </div>
                    {% for form in formset %}
                    <div class="ingredient-form form-row">
                        <div class="col-6">
                            {{ form.ingredient | as_crispy_field}}
                        </div>
                        <div class="col-2">
                            {{ form.quantity | as_crispy_field}}
                        </div>
                        <div class="col-3">
                            {{ form.measurement | as_crispy_field}}
                        </div> 
                        <div class="col-1">
                            <button class="btn-secondary btn" id="add-form" type="button" onclick="addForm();">+</button>
                        </div>
                    </div>
                    {% endfor %}
                <div id="add-ingredient">
                    <button class="btn-primary btn float-right" type="submit">Submit</button>
                </div>
            </div>           
        </div>
    </form>
    
<script>
    
    let ingredientForm = document.querySelectorAll(".ingredient-form")
    let container = document.querySelector("#form-container")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    let sumbitDiv = document.querySelector("#add-ingredient")
    
    let formNum = ingredientForm.length-1

    function addForm(){
        let newForm = ingredientForm[0].cloneNode(true)
        let formRegex = RegExp(`form-(\\d){1}-`,'g')

        formNum++
        newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
        newForm.innerHTML = newForm.innerHTML.replace(/value\s*=\s*(['"])?(.*?)\1/gi, '')

        container.insertBefore(newForm, sumbitDiv)

        totalForms.setAttribute('value', `${formNum+1}`)
    }
</script>
<!--
<script>
    document.getElementById("recipeform").addEventListener("submit", function() {
        window.onbeforeunload = null;
    });
    window.onbeforeunload = function() {
        return "";
    };
</script>
-->
{% endblock %}

meals/templates/meals/recipe_url_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn-primary btn" type="submit">Submit</button>
    </form>
    
    
{% endblock %}

meals/templates/meals/recipes_list.html
{% extends "base.html" %}
{% block content %}
<h1>Recipes</h1>
<div class="row">
    {% for recipe in page_obj %}

        <div class="col-4">
            <a href="{% url 'meals:recipe-view' recipe.id %}">{{ recipe.title|title }}</a>
        </div>    
    {% endfor %}
</div>

<div class="pagination d-flex justify-content-center">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
        {% endif %}
    </span>
</div>
{% endblock %}